query GetAllCompanies {
    allCompanies {
        id
        name
        industry
        employees {
            id
            firstName
            lastName
            status
            address
        }
    }
}